export const FEATURED_COLLECTION_REQUEST = "FEATURED_COLLECTION_REQUEST";
export const FEATURED_COLLECTION_SUCCESS = "FEATURED_COLLECTION_SUCCESS";
export const FEATURED_COLLECTION_FAIL = "FEATURED_COLLECTION_FAIL";