export const PRODUCT_VARIANT_CHANGE = "PRODUCT_VARIANT_CHANGE";
export const PRODUCT_VARIANT_CHANGE_REQUEST = "PRODUCT_VARIANT_CHANGE_REQUEST";
export const PRODUCT_VARIANT_CHANGE_FAIL = "PRODUCT_VARIANT_CHANGE_FAIL";